name: New Article from Email
on:
  repository_dispatch:
    types: [new-article]

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      TITLE: ${{ github.event.client_payload.title }}
      ARTICLE_URL: ${{ github.event.client_payload.url }}
    steps:
      - uses: actions/checkout@v6

      - name: Render user.txt from template
        working-directory: ./_scripts
        env:
          TITLE: ${{ github.event.client_payload.title }}
          ARTICLE_URL: ${{ github.event.client_payload.url }}
        run: |
          envsubst '${TITLE} ${ARTICLE_URL}' < user_template.txt > user.txt

      - name: Run Groq script
        working-directory: ./_scripts
        run: |
          cat system.txt
          cat user.txt
          bash ./ai_summary.sh   
          cat result.md

      - name: Build article 
        working-directory: ./_scripts
        run: |
          bash ./build_article.sh ${{ env.TITLE }} ${{ env.ARTICLE_URL }}
      # - name: Commit new article
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: "Add article: ${{ env.TITLE }}"