name: Sanity Check
on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    env:
      TITLE: "test google.com"
      ARTICLE_URL: "https://www.google.com"
      TITLE2: "test 2 google.com"
    steps:
      - uses: actions/checkout@v6

      - name: Input sanity check
        working-directory: ./_scripts
        env:
          TITLE: "test google.com"
          ARTICLE_URL: ${{ env.ARTICLE_URL }}
        run: |
          bash test_envvars.sh

